import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, BrainCircuit, Eye, Heart, Loader2, MessageCircle, MousePointerClick, RefreshCw, Sparkles, TrendingUp, Users } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { PlanGate } from "@/components/PlanGate";
import { generateAnalyticsInsight, listListeningMentions, listSocialMetrics, syncSocialMetrics } from "@/lib/social.functions";
import { getAccessKey } from "@/lib/session";

export const Route = createFileRoute("/analytics")({ head: () => ({ meta: [{ title: "Analytics — Zunexi.ai" }] }), component: AnalyticsRoute });
type Metric = { id: string; platform: string; metric_date: string; followers: number; reach: number; impressions: number; engagements: number; likes: number; comments: number; shares: number; saves: number; clicks: number; views: number; social_accounts?: { account_name?: string; username?: string } };
type Mention = { id: string; platform: string; author_name: string; text: string; sentiment: string; occurred_at: string; social_accounts?: { account_name?: string } };
function AnalyticsRoute() { return <AppShell><PlanGate feature="analytics"><AnalyticsPage /></PlanGate></AppShell>; }
function isoDate(date: Date) { return date.toISOString().slice(0, 10); }

function AnalyticsPage() {
  const accessKey = getAccessKey() || "";
  const getMetrics = useServerFn(listSocialMetrics); const sync = useServerFn(syncSocialMetrics); const insightFn = useServerFn(generateAnalyticsInsight); const mentionsFn = useServerFn(listListeningMentions);
  const [from, setFrom] = useState(isoDate(new Date(Date.now() - 29 * 86400000))); const [to, setTo] = useState(isoDate(new Date()));
  const [metrics, setMetrics] = useState<Metric[]>([]); const [mentions, setMentions] = useState<Mention[]>([]); const [insight, setInsight] = useState(""); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false);
  async function refresh() { setLoading(true); try { setMetrics(await getMetrics({ data: { accessKey, from, to, brandId: null } }) as Metric[]); try { setMentions(await mentionsFn({ data: { accessKey, limit: 20 } }) as Mention[]); } catch { setMentions([]); } } catch (e) { toast.error((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, [from, to]);
  const totals = useMemo(() => metrics.reduce((a, r) => ({ followers: a.followers + Number(r.followers || 0), reach: a.reach + Number(r.reach || 0), impressions: a.impressions + Number(r.impressions || 0), engagements: a.engagements + Number(r.engagements || 0), likes: a.likes + Number(r.likes || 0), comments: a.comments + Number(r.comments || 0), clicks: a.clicks + Number(r.clicks || 0), views: a.views + Number(r.views || 0) }), { followers: 0, reach: 0, impressions: 0, engagements: 0, likes: 0, comments: 0, clicks: 0, views: 0 }), [metrics]);
  async function syncNow() { setWorking(true); try { const result = await sync({ data: { accessKey, accountId: null } }) as Array<{status:string}>; const ok = result.filter((r) => r.status === "success").length; toast.success(`${ok} conta(s) sincronizada(s).`); await refresh(); } catch (e) { toast.error((e as Error).message); } finally { setWorking(false); } }
  async function generate() { setWorking(true); try { setInsight(await insightFn({ data: { accessKey, from, to } })); } catch (e) { toast.error((e as Error).message); } finally { setWorking(false); } }
  const byPlatform = useMemo(() => Object.values(metrics.reduce((map: Record<string, any>, row) => { const key = row.platform; map[key] ||= { platform: key, followers: 0, reach: 0, engagements: 0, views: 0 }; for (const field of ["followers", "reach", "engagements", "views"]) map[key][field] += Number((row as any)[field] || 0); return map; }, {})), [metrics]);

  return <div className="page-wrap space-y-6"><section className="studio-hero panel relative overflow-hidden p-6 sm:p-8"><div className="studio-hero-grid" /><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="eyebrow mb-3 flex items-center gap-2"><BarChart3 className="h-3.5 w-3.5 text-primary" /> Desempenho</div><h1 className="section-title text-3xl sm:text-5xl">Analytics</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">Métricas das contas conectadas, histórico por período e recomendações geradas pela Groq.</p></div><div className="flex flex-wrap gap-2"><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="app-input h-11" /><input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="app-input h-11" /><button onClick={() => void syncNow()} disabled={working} className="secondary-button"><RefreshCw className={`h-4 w-4 ${working ? "animate-spin" : ""}`} /> Sincronizar</button></div></div></section>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Seguidores registrados" value={totals.followers} icon={Users} /><MetricCard label="Alcance" value={totals.reach} icon={TrendingUp} /><MetricCard label="Interações" value={totals.engagements} icon={Heart} /><MetricCard label="Visualizações" value={totals.views} icon={Eye} /></section>
  <section className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="panel overflow-hidden"><div className="border-b border-border p-5"><h2 className="section-title text-xl">Resultados por rede</h2><p className="mt-1 text-xs text-muted-foreground">Somatório dos registros no período selecionado.</p></div>{loading ? <div className="grid min-h-64 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div> : byPlatform.length === 0 ? <div className="grid min-h-64 place-items-center p-8 text-center text-sm text-muted-foreground">Conecte uma conta e clique em Sincronizar para começar.</div> : <div className="divide-y divide-border">{byPlatform.map((row: any) => <div key={row.platform} className="grid gap-3 p-5 sm:grid-cols-5 sm:items-center"><strong className="capitalize">{row.platform.replace("_", " ")}</strong><SmallStat label="Seguidores" value={row.followers} /><SmallStat label="Alcance" value={row.reach} /><SmallStat label="Interações" value={row.engagements} /><SmallStat label="Views" value={row.views} /></div>)}</div>}</div>
  <div className="panel p-5"><div className="flex items-center justify-between gap-3"><div><div className="eyebrow flex items-center gap-2"><BrainCircuit className="h-3.5 w-3.5 text-primary" /> Consultor Zunexi</div><h2 className="section-title mt-2 text-xl">Leitura estratégica</h2></div><button onClick={() => void generate()} disabled={working} className="primary-button">{working ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />} Analisar</button></div><div className="mt-5 min-h-52 whitespace-pre-wrap rounded-2xl border border-border bg-secondary/30 p-4 text-sm leading-7 text-muted-foreground">{insight || "Clique em Analisar para receber um resumo do período, pontos de atenção e ações para os próximos sete dias."}</div></div></section>
  <section className="panel overflow-hidden"><div className="border-b border-border p-5"><h2 className="section-title text-xl">Menções e comentários recentes</h2><p className="mt-1 text-xs text-muted-foreground">Disponível no plano Agência quando os webhooks das redes estiverem conectados.</p></div>{mentions.length === 0 ? <div className="p-8 text-center text-sm text-muted-foreground">Nenhuma menção sincronizada neste momento.</div> : <div className="divide-y divide-border">{mentions.map((mention) => <div key={mention.id} className="p-5"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm">{mention.author_name || "Usuário da rede"}</strong><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${mention.sentiment === "urgent" || mention.sentiment === "negative" ? "bg-red-500/10 text-red-600" : mention.sentiment === "positive" ? "bg-emerald-500/10 text-emerald-600" : "bg-secondary text-muted-foreground"}`}>{mention.sentiment}</span></div><p className="mt-2 text-sm text-muted-foreground">{mention.text}</p><div className="mt-2 text-[10px] text-muted-foreground">{mention.social_accounts?.account_name || mention.platform} · {new Date(mention.occurred_at).toLocaleString("pt-BR")}</div></div>)}</div>}</section>
  </div>;
}
function MetricCard({label,value,icon:Icon}:{label:string;value:number;icon:any}) { return <div className="metric-card panel p-5"><div className="flex items-center justify-between"><div><div className="text-2xl font-bold">{value.toLocaleString("pt-BR")}</div><div className="mt-1 text-xs text-muted-foreground">{label}</div></div><div className="grid h-11 w-11 place-items-center rounded-2xl bg-primary/10 text-primary"><Icon className="h-5 w-5" /></div></div></div>; }
function SmallStat({label,value}:{label:string;value:number}) { return <div><div className="text-sm font-semibold">{Number(value).toLocaleString("pt-BR")}</div><div className="text-[10px] text-muted-foreground">{label}</div></div>; }
