import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState, type FormEvent } from "react";
import { Activity, Check, Clock3, Loader2, Play, Plus, Power, Trash2, Workflow, X } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { PlanGate } from "@/components/PlanGate";
import { deleteAutomationRule, listAutomationRules, runAutomationRule, saveAutomationRule } from "@/lib/social.functions";
import { getAccessKey } from "@/lib/session";

export const Route = createFileRoute("/automacoes")({ head: () => ({ meta: [{ title: "Automações — Zunexi.ai" }] }), component: AutomationsRoute });
type RuleType="publicar_aprovado"|"responder_palavra"|"alertar_reclamacao"|"lembrar_aprovacao"|"alertar_desempenho"|"preencher_calendario";
type Rule={id:string;name:string;rule_type:RuleType;active:boolean;trigger_config:any;action_config:any;last_run_at:string|null;created_at:string}; type Run={id:string;status:string;message:string;created_at:string;automation_rule_id:string|null};
const TYPES:Record<RuleType,{label:string;description:string}>={publicar_aprovado:{label:"Publicar agendados",description:"Publica conteúdos aprovados quando o horário chegar."},responder_palavra:{label:"Resposta por palavra",description:"Responde automaticamente mensagens com palavras definidas."},alertar_reclamacao:{label:"Alertar reclamações",description:"Registra alertas quando chegam interações negativas ou urgentes."},lembrar_aprovacao:{label:"Lembrar aprovação",description:"Avisa quando um conteúdo espera revisão por tempo demais."},alertar_desempenho:{label:"Alertar desempenho",description:"Destaca métricas acima do limite de interações."},preencher_calendario:{label:"Preencher calendário",description:"Avisa quando faltam conteúdos nos próximos sete dias."}};
function AutomationsRoute(){return <AppShell><PlanGate feature="automacoes"><AutomationsPage/></PlanGate></AppShell>}
function AutomationsPage(){const accessKey=getAccessKey()||"";const list=useServerFn(listAutomationRules);const save=useServerFn(saveAutomationRule);const remove=useServerFn(deleteAutomationRule);const run=useServerFn(runAutomationRule);const[rules,setRules]=useState<Rule[]>([]);const[runs,setRuns]=useState<Run[]>([]);const[loading,setLoading]=useState(true);const[working,setWorking]=useState<string|null>(null);const[modal,setModal]=useState(false);const[name,setName]=useState("");const[type,setType]=useState<RuleType>("publicar_aprovado");const[keywords,setKeywords]=useState("");const[response,setResponse]=useState("");const[value,setValue]=useState("24");
async function refresh(){setLoading(true);try{const data=await list({data:{accessKey}}) as any;setRules(data.rules);setRuns(data.runs)}catch(e){toast.error((e as Error).message)}finally{setLoading(false)}}useEffect(()=>{void refresh()},[]);
function open(){setName("");setType("publicar_aprovado");setKeywords("");setResponse("");setValue("24");setModal(true)}
function config(){if(type==="responder_palavra")return{triggerConfig:{keywords:keywords.split(",").map(x=>x.trim()).filter(Boolean)},actionConfig:{response}};if(type==="lembrar_aprovacao")return{triggerConfig:{hours:Number(value)||24},actionConfig:{}};if(type==="alertar_desempenho")return{triggerConfig:{engagements:Number(value)||100},actionConfig:{}};if(type==="preencher_calendario")return{triggerConfig:{minimum:Number(value)||3},actionConfig:{}};return{triggerConfig:{},actionConfig:{}}}
async function submit(e:FormEvent){e.preventDefault();const c=config();try{await save({data:{accessKey,rule:{brandId:null,name,ruleType:type,active:true,...c}}});toast.success("Automação criada.");setModal(false);await refresh()}catch(err){toast.error((err as Error).message)}}
async function toggle(rule:Rule){try{await save({data:{accessKey,rule:{id:rule.id,brandId:null,name:rule.name,ruleType:rule.rule_type,active:!rule.active,triggerConfig:rule.trigger_config||{},actionConfig:rule.action_config||{}}}});await refresh()}catch(e){toast.error((e as Error).message)}}
async function execute(rule:Rule){setWorking(rule.id);try{await run({data:{accessKey,id:rule.id}});toast.success("Automação executada.");await refresh()}catch(e){toast.error((e as Error).message)}finally{setWorking(null)}}
async function del(rule:Rule){if(!confirm(`Excluir “${rule.name}”?`))return;try{await remove({data:{accessKey,id:rule.id}});await refresh()}catch(e){toast.error((e as Error).message)}}
return <div className="page-wrap space-y-6"><section className="studio-hero panel relative overflow-hidden p-6 sm:p-8"><div className="studio-hero-grid"/><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="eyebrow mb-3 flex items-center gap-2"><Workflow className="h-3.5 w-3.5 text-primary"/> Fluxos automáticos</div><h1 className="section-title text-3xl sm:text-5xl">Automações</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">Publicação programada, respostas por palavra-chave e alertas operacionais sem tarefas repetitivas.</p></div><button onClick={open} className="primary-button"><Plus className="h-4 w-4"/> Nova automação</button></div></section>
<section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><div className="panel overflow-hidden"><div className="border-b border-border p-5"><h2 className="section-title text-xl">Regras ativas</h2><p className="mt-1 text-xs text-muted-foreground">O cron da Vercel verifica regras e publicações agendadas.</p></div>{loading?<div className="grid min-h-64 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary"/></div>:rules.length===0?<div className="p-10 text-center text-sm text-muted-foreground">Nenhuma automação criada.</div>:<div className="divide-y divide-border">{rules.map(rule=><div key={rule.id} className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 gap-3"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${rule.active?"bg-primary/10 text-primary":"bg-secondary text-muted-foreground"}`}><Power className="h-5 w-5"/></div><div><h3 className="font-semibold">{rule.name}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{TYPES[rule.rule_type].description}</p><p className="mt-1 text-[10px] text-muted-foreground">Última execução: {rule.last_run_at?new Date(rule.last_run_at).toLocaleString("pt-BR"):"ainda não executada"}</p></div></div><div className="flex gap-1"><button onClick={()=>void toggle(rule)} className={`rounded-xl px-3 py-2 text-xs font-semibold ${rule.active?"bg-emerald-500/10 text-emerald-600":"bg-secondary text-muted-foreground"}`}>{rule.active?"Ativa":"Pausada"}</button><button onClick={()=>void execute(rule)} disabled={working===rule.id} className="rounded-xl p-2 text-primary hover:bg-primary/10">{working===rule.id?<Loader2 className="h-4 w-4 animate-spin"/>:<Play className="h-4 w-4"/>}</button><button onClick={()=>void del(rule)} className="rounded-xl p-2 text-red-500 hover:bg-red-500/10"><Trash2 className="h-4 w-4"/></button></div></div></div>)}</div>}</div>
<div className="panel overflow-hidden"><div className="border-b border-border p-5"><h2 className="section-title text-xl">Histórico</h2><p className="mt-1 text-xs text-muted-foreground">Últimas verificações e ações.</p></div><div className="max-h-[560px] divide-y divide-border overflow-y-auto">{runs.length===0?<div className="p-8 text-center text-sm text-muted-foreground">Sem execuções registradas.</div>:runs.map(item=><div key={item.id} className="p-4"><div className="flex items-start gap-3"><div className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${item.status==="success"?"bg-emerald-500":item.status==="failed"?"bg-red-500":"bg-amber-500"}`}/><div><p className="text-xs leading-5">{item.message}</p><div className="mt-1 flex items-center gap-1 text-[10px] text-muted-foreground"><Clock3 className="h-3 w-3"/>{new Date(item.created_at).toLocaleString("pt-BR")}</div></div></div></div>)}</div></div></section>
{modal&&<div className="fixed inset-0 z-[80] grid place-items-center bg-black/60 p-4 backdrop-blur-sm"><form onSubmit={submit} className="panel w-full max-w-xl p-6"><div className="flex items-center justify-between"><div><div className="eyebrow">Nova regra</div><h2 className="section-title mt-2 text-2xl">Configurar automação</h2></div><button type="button" onClick={()=>setModal(false)} className="rounded-xl p-2 hover:bg-secondary"><X className="h-5 w-5"/></button></div><div className="mt-6 space-y-4"><label className="block"><span className="mb-2 block text-xs font-semibold">Nome</span><input required minLength={2} value={name} onChange={e=>setName(e.target.value)} className="app-input w-full" placeholder="Ex.: Publicação automática"/></label><label className="block"><span className="mb-2 block text-xs font-semibold">Tipo</span><select value={type} onChange={e=>setType(e.target.value as RuleType)} className="app-input w-full">{Object.entries(TYPES).map(([v,m])=><option key={v} value={v}>{m.label}</option>)}</select></label>{type==="responder_palavra"&&<><label className="block"><span className="mb-2 block text-xs font-semibold">Palavras separadas por vírgula</span><input required value={keywords} onChange={e=>setKeywords(e.target.value)} className="app-input w-full" placeholder="preço, horário, cardápio"/></label><label className="block"><span className="mb-2 block text-xs font-semibold">Resposta automática</span><textarea required value={response} onChange={e=>setResponse(e.target.value)} rows={4} className="app-input w-full resize-none py-3"/></label></>}{["lembrar_aprovacao","alertar_desempenho","preencher_calendario"].includes(type)&&<label className="block"><span className="mb-2 block text-xs font-semibold">{type==="lembrar_aprovacao"?"Horas em espera":type==="alertar_desempenho"?"Mínimo de interações":"Mínimo de posts na semana"}</span><input type="number" min={1} value={value} onChange={e=>setValue(e.target.value)} className="app-input w-full"/></label>}<button className="primary-button w-full"><Check className="h-4 w-4"/> Salvar automação</button></div></form></div>}</div>}
