import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState, type FormEvent } from "react";
import { Check, Clipboard, KeyRound, Loader2, Pencil, Plus, ShieldCheck, Trash2, UsersRound, X } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { PlanGate } from "@/components/PlanGate";
import { createTeamMember, deleteTeamMember, listTeamMembers, updateTeamMember } from "@/lib/team.functions";
import { getAccessKey } from "@/lib/session";

export const Route = createFileRoute("/equipe")({ head: () => ({ meta: [{ title: "Equipe — Zunexi.ai" }] }), component: TeamRoute });
type Role = "admin" | "social" | "designer" | "approver" | "analyst" | "viewer" | "support" | "member";
type Member = { id:string; display_name:string; role:Role|"owner"; active:boolean; created_at:string; access_keys?: { key?:string; last_used_at?:string; uses?:number; active?:boolean } | Array<any> };
const ROLES: Record<Role, string> = { admin:"Administrador", social:"Social media", designer:"Designer", approver:"Aprovador", analyst:"Analista", viewer:"Somente leitura", support:"Atendimento", member:"Membro" };
function TeamRoute(){ return <AppShell><PlanGate feature="equipe"><TeamPage /></PlanGate></AppShell>; }
function TeamPage(){
 const accessKey=getAccessKey()||""; const getMembers=useServerFn(listTeamMembers); const createMember=useServerFn(createTeamMember); const editMember=useServerFn(updateTeamMember); const removeMember=useServerFn(deleteTeamMember);
 const [members,setMembers]=useState<Member[]>([]); const [loading,setLoading]=useState(true); const [modal,setModal]=useState(false); const [editing,setEditing]=useState<Member|null>(null); const [name,setName]=useState(""); const [role,setRole]=useState<Role>("social"); const [active,setActive]=useState(true); const [saving,setSaving]=useState(false); const [newKey,setNewKey]=useState("");
 async function refresh(){setLoading(true);try{const data=await getMembers({data:{accessKey}}) as {members:Member[]};setMembers(data.members);}catch(e){toast.error((e as Error).message);}finally{setLoading(false)}} useEffect(()=>{void refresh()},[]);
 function openCreate(){setEditing(null);setName("");setRole("social");setActive(true);setNewKey("");setModal(true)} function openEdit(m:Member){if(m.role==="owner")return;setEditing(m);setName(m.display_name);setRole(m.role as Role);setActive(m.active);setNewKey("");setModal(true)}
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);try{if(editing){await editMember({data:{accessKey,memberId:editing.id,displayName:name,role,active}});toast.success("Membro atualizado.");setModal(false);}else{const result=await createMember({data:{accessKey,displayName:name,role}}) as any;setNewKey(result.access_key);toast.success("Acesso criado. Copie a chave antes de fechar.");}await refresh();}catch(err){toast.error((err as Error).message)}finally{setSaving(false)}}
 async function remove(m:Member){if(!confirm(`Excluir o acesso de ${m.display_name}?`))return;try{await removeMember({data:{accessKey,memberId:m.id}});toast.success("Acesso removido.");await refresh();}catch(e){toast.error((e as Error).message)}}
 async function copyKey(value:string){await navigator.clipboard.writeText(value);toast.success("Chave copiada.")}
 return <div className="page-wrap space-y-6"><section className="studio-hero panel relative overflow-hidden p-6 sm:p-8"><div className="studio-hero-grid"/><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="eyebrow mb-3 flex items-center gap-2"><UsersRound className="h-3.5 w-3.5 text-primary"/> Plano Agência</div><h1 className="section-title text-3xl sm:text-5xl">Equipe</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">Crie acessos separados e controle quem cria, revisa, aprova, atende ou apenas acompanha.</p></div><button onClick={openCreate} className="primary-button"><Plus className="h-4 w-4"/> Novo membro</button></div></section>
 <section className="panel overflow-hidden"><div className="grid grid-cols-[minmax(0,1fr)_140px_90px] gap-3 border-b border-border px-5 py-3 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground sm:grid-cols-[minmax(0,1fr)_180px_130px_110px]"><span>Membro</span><span>Função</span><span className="hidden sm:block">Uso</span><span>Ações</span></div>{loading?<div className="grid min-h-64 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary"/></div>:members.map(m=>{const key=Array.isArray(m.access_keys)?m.access_keys[0]:m.access_keys;return <div key={m.id} className="grid grid-cols-[minmax(0,1fr)_140px_90px] gap-3 border-b border-border/70 px-5 py-4 sm:grid-cols-[minmax(0,1fr)_180px_130px_110px] sm:items-center"><div className="min-w-0"><div className="flex items-center gap-2"><strong className="truncate text-sm">{m.display_name}</strong>{m.role==="owner"&&<ShieldCheck className="h-4 w-4 text-primary"/>}</div><div className="mt-1 flex items-center gap-1.5 text-[10px] text-muted-foreground"><span className={`h-2 w-2 rounded-full ${m.active?"bg-emerald-500":"bg-red-500"}`}/>{m.active?"Ativo":"Desativado"}</div></div><div className="text-xs">{m.role==="owner"?"Proprietário":ROLES[m.role as Role]||m.role}</div><div className="hidden text-xs text-muted-foreground sm:block">{Number(key?.uses||0)} acessos</div><div className="flex gap-1">{m.role!=="owner"&&<><button onClick={()=>openEdit(m)} className="rounded-lg p-2 text-muted-foreground hover:bg-secondary hover:text-foreground"><Pencil className="h-4 w-4"/></button><button onClick={()=>void remove(m)} className="rounded-lg p-2 text-red-500 hover:bg-red-500/10"><Trash2 className="h-4 w-4"/></button></>}</div></div>})}</section>
 {modal&&<div className="fixed inset-0 z-[80] grid place-items-center bg-black/60 p-4 backdrop-blur-sm"><div className="panel w-full max-w-lg p-6"><div className="flex items-center justify-between"><div><div className="eyebrow">{editing?"Editar acesso":"Novo acesso"}</div><h2 className="section-title mt-2 text-2xl">{editing?editing.display_name:"Adicionar à equipe"}</h2></div><button onClick={()=>setModal(false)} className="rounded-xl p-2 hover:bg-secondary"><X className="h-5 w-5"/></button></div>{newKey?<div className="mt-6"><div className="rounded-2xl border border-emerald-500/25 bg-emerald-500/10 p-5"><div className="flex items-center gap-2 text-sm font-semibold text-emerald-700 dark:text-emerald-300"><KeyRound className="h-4 w-4"/> Chave criada</div><p className="mt-2 text-xs leading-5 text-muted-foreground">Ela permite entrar na mesma empresa pelo celular ou computador. Guarde-a em local seguro.</p><button onClick={()=>void copyKey(newKey)} className="mt-4 flex w-full items-center justify-between rounded-xl border border-border bg-card px-4 py-3 font-mono text-sm"><span>{newKey}</span><Clipboard className="h-4 w-4 text-primary"/></button></div><button onClick={()=>setModal(false)} className="primary-button mt-4 w-full"><Check className="h-4 w-4"/> Concluir</button></div>:<form onSubmit={submit} className="mt-6 space-y-4"><label className="block"><span className="mb-2 block text-xs font-semibold">Nome</span><input required minLength={2} value={name} onChange={e=>setName(e.target.value)} className="app-input w-full" placeholder="Ex.: Ana — Social Media"/></label><label className="block"><span className="mb-2 block text-xs font-semibold">Função</span><select value={role} onChange={e=>setRole(e.target.value as Role)} className="app-input w-full">{Object.entries(ROLES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{editing&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Acesso ativo</label>}<button disabled={saving} className="primary-button w-full">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Check className="h-4 w-4"/>}{editing?"Salvar alterações":"Criar chave de acesso"}</button></form>}</div></div>}
 </div>;
}
