/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CriadorPromptsRouteImport } from './routes/criador-prompts'
import { Route as CartazRouteImport } from './routes/cartaz'
import { Route as CarrosselRouteImport } from './routes/carrossel'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorIdRouteImport } from './routes/editor.$id'
import { Route as PublicacoesRouteImport } from './routes/publicacoes'
import { Route as RedesRouteImport } from './routes/redes'
import { Route as CaixaEntradaRouteImport } from './routes/caixa-entrada'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as EquipeRouteImport } from './routes/equipe'

const PublicacoesRoute = PublicacoesRouteImport.update({
  id: '/publicacoes',
  path: '/publicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RedesRoute = RedesRouteImport.update({
  id: '/redes',
  path: '/redes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaEntradaRoute = CaixaEntradaRouteImport.update({
  id: '/caixa-entrada',
  path: '/caixa-entrada',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const CriadorPromptsRoute = CriadorPromptsRouteImport.update({
  id: '/criador-prompts',
  path: '/criador-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CartazRoute = CartazRouteImport.update({
  id: '/cartaz',
  path: '/cartaz',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrosselRoute = CarrosselRouteImport.update({
  id: '/carrossel',
  path: '/carrossel',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/publicacoes': typeof PublicacoesRoute
  '/redes': typeof RedesRoute
  '/caixa-entrada': typeof CaixaEntradaRoute
  '/analytics': typeof AnalyticsRoute
  '/automacoes': typeof AutomacoesRoute
  '/equipe': typeof EquipeRoute
  '/acesso': typeof AcessoRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/brand-kit': typeof BrandKitRoute
  '/biblioteca': typeof BibliotecaRoute
  '/carrossel': typeof CarrosselRoute
  '/cartaz': typeof CartazRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criador-prompts': typeof CriadorPromptsRoute
  '/projetos': typeof ProjetosRoute
  '/editor/$id': typeof EditorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/publicacoes': typeof PublicacoesRoute
  '/redes': typeof RedesRoute
  '/caixa-entrada': typeof CaixaEntradaRoute
  '/analytics': typeof AnalyticsRoute
  '/automacoes': typeof AutomacoesRoute
  '/equipe': typeof EquipeRoute
  '/acesso': typeof AcessoRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/brand-kit': typeof BrandKitRoute
  '/biblioteca': typeof BibliotecaRoute
  '/carrossel': typeof CarrosselRoute
  '/cartaz': typeof CartazRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criador-prompts': typeof CriadorPromptsRoute
  '/projetos': typeof ProjetosRoute
  '/editor/$id': typeof EditorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/publicacoes': typeof PublicacoesRoute
  '/redes': typeof RedesRoute
  '/caixa-entrada': typeof CaixaEntradaRoute
  '/analytics': typeof AnalyticsRoute
  '/automacoes': typeof AutomacoesRoute
  '/equipe': typeof EquipeRoute
  '/acesso': typeof AcessoRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/brand-kit': typeof BrandKitRoute
  '/biblioteca': typeof BibliotecaRoute
  '/carrossel': typeof CarrosselRoute
  '/cartaz': typeof CartazRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criador-prompts': typeof CriadorPromptsRoute
  '/projetos': typeof ProjetosRoute
  '/editor/$id': typeof EditorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/publicacoes'
    | '/redes'
    | '/caixa-entrada'
    | '/analytics'
    | '/automacoes'
    | '/equipe'
    | '/acesso'
    | '/agenda'
    | '/brand-kit'
    | '/admin'
    | '/biblioteca'
    | '/carrossel'
    | '/cartaz'
    | '/configuracoes'
    | '/criador-prompts'
    | '/projetos'
    | '/editor/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/publicacoes'
    | '/redes'
    | '/caixa-entrada'
    | '/analytics'
    | '/automacoes'
    | '/equipe'
    | '/acesso'
    | '/agenda'
    | '/brand-kit'
    | '/admin'
    | '/biblioteca'
    | '/carrossel'
    | '/cartaz'
    | '/configuracoes'
    | '/criador-prompts'
    | '/projetos'
    | '/editor/$id'
  id:
    | '__root__'
    | '/'
    | '/publicacoes'
    | '/redes'
    | '/caixa-entrada'
    | '/analytics'
    | '/automacoes'
    | '/equipe'
    | '/acesso'
    | '/agenda'
    | '/brand-kit'
    | '/admin'
    | '/biblioteca'
    | '/carrossel'
    | '/cartaz'
    | '/configuracoes'
    | '/criador-prompts'
    | '/projetos'
    | '/editor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicacoesRoute: typeof PublicacoesRoute
  RedesRoute: typeof RedesRoute
  CaixaEntradaRoute: typeof CaixaEntradaRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AutomacoesRoute: typeof AutomacoesRoute
  EquipeRoute: typeof EquipeRoute
  AcessoRoute: typeof AcessoRoute
  AgendaRoute: typeof AgendaRoute
  BrandKitRoute: typeof BrandKitRoute
  AdminRoute: typeof AdminRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CarrosselRoute: typeof CarrosselRoute
  CartazRoute: typeof CartazRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CriadorPromptsRoute: typeof CriadorPromptsRoute
  ProjetosRoute: typeof ProjetosRoute
  EditorIdRoute: typeof EditorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publicacoes': {
      id: '/publicacoes'
      path: '/publicacoes'
      fullPath: '/publicacoes'
      preLoaderRoute: typeof PublicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redes': {
      id: '/redes'
      path: '/redes'
      fullPath: '/redes'
      preLoaderRoute: typeof RedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa-entrada': {
      id: '/caixa-entrada'
      path: '/caixa-entrada'
      fullPath: '/caixa-entrada'
      preLoaderRoute: typeof CaixaEntradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criador-prompts': {
      id: '/criador-prompts'
      path: '/criador-prompts'
      fullPath: '/criador-prompts'
      preLoaderRoute: typeof CriadorPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartaz': {
      id: '/cartaz'
      path: '/cartaz'
      fullPath: '/cartaz'
      preLoaderRoute: typeof CartazRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrossel': {
      id: '/carrossel'
      path: '/carrossel'
      fullPath: '/carrossel'
      preLoaderRoute: typeof CarrosselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicacoesRoute: PublicacoesRoute,
  RedesRoute: RedesRoute,
  CaixaEntradaRoute: CaixaEntradaRoute,
  AnalyticsRoute: AnalyticsRoute,
  AutomacoesRoute: AutomacoesRoute,
  EquipeRoute: EquipeRoute,
  AcessoRoute: AcessoRoute,
  AgendaRoute: AgendaRoute,
  BrandKitRoute: BrandKitRoute,
  AdminRoute: AdminRoute,
  BibliotecaRoute: BibliotecaRoute,
  CarrosselRoute: CarrosselRoute,
  CartazRoute: CartazRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CriadorPromptsRoute: CriadorPromptsRoute,
  ProjetosRoute: ProjetosRoute,
  EditorIdRoute: EditorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
